kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: yml-nginx-deployment
spec:
  replicas: 3
  strategy: Recreate
  selector:
    matchLabels:
      deploy: example
  template:
    metadata:
      labels:
        deploy: example
    spec:
      # $.spec.template.spec.securityContext.runAsUser any equal 0
      securityContext:
        runAsUser: 10000
      containers:
        - name: nginx
          image: nginx:1.7.9
          securityContext:
            # $.spec.template.spec.containers[*].securityContext.readOnlyRootFilesystem exists and $.spec.template.spec.containers[*].securityContext.readOnlyRootFilesystem any false
            readOnlyRootFilesystem: true
            # $.spec.template.spec.containers[*].securityContext.privileged any true
            privileged: false
            # $.spec.template.spec.containers[*].securityContext.runAsNonRoot equals false
            runAsNonRoot: true
            capabilities:
              drop:
                # $.spec.template.spec.containers[*].securityContext.capabilities.drop exists and not $.spec.templates.spec.containers[*].securityContext.capabilities.drop[*] contains ALL
                - ALL
                # $.spec.template.spec.containers[*].securityContext.capabilities exists and $.spec.template.spec.containers[*].securityContext.capabilities.add[*] is member of (FSETID, SETUID, SETGID,SYS_CHROOT,SYS_PTRACE,CHOWN,NET_RAW,NET_ADMIN,SYS_ADMIN,NET_BIND_SERVICE)
        - name: nginx
          image: nginx:1.8.0
          securityContext:
            capabilities:
              drop:
                # $.spec.template.spec.containers[*].securityContext.capabilities.drop exists and not $.spec.templates.spec.containers[*].securityContext.capabilities.drop[*] contains ALL
                - ALL
            # $.spec.template.spec.containers[*].securityContext.runAsUser < 9999
            runAsUser: 9999
      # $.spec.template.spec.hostIPC is true
      hostIPC: false
      # $.spec.template.spec.hostPID is true
      hostPID: false
      # $.spec.template.spec.hostNetwork is true
      hostNetwork: false
  volumeClaimTemplates:
    - spec:
        accessModes:
          - ReadOnly
          # $.spec.volumeClaimTemplates[*].spec.accessModes contains ReadWriteMany
          - ReadWrite



# Modified [k8s_all_issues_addressed.yml] on [2020-11-30 22:59:01.217455]